name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run CI.ps1
      run: |
        cd $GITHUB_WORKSPACE
        pwsh CI.ps1
